name: Checks

on:
  pull_request_target:
    types: [opened, synchronize]

concurrency:
  group: pr-checks-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      test-chunks: ${{ steps['set-test-chunks'].outputs['test-chunks'] }}
      test-chunk-ids: ${{ steps['set-test-chunk-ids'].outputs['test-chunk-ids'] }}
      yarn-cache-hit: ${{ steps.cache-yarn-cache.outputs.yarn-cache-hit }}
      node-modules-cache-hit: ${{ steps.cache-node-modules.outputs.node-modules-cache-hit }}
    steps:
      - name: Checkout creating chunks
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
      - id: yarn-cache-dir-path
        name: Get yarn cache directory path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - id: cache-yarn-cache
        name: Cache yarn cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
              ${{ runner.os }}-yarn-
      - id: cache-node-modules
        name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
              ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-
      - name: Install Deps
        run: yarn install --frozen-lockfile
      - id: set-test-chunks
        name: Set Chunks
        run: echo "::set-output name=test-chunks::$(yarn --silent jest --listTests --json | jq -cM '[_nwise(length / 2 | floor)]')"
      - id: set-test-chunk-ids
        name: Set Chunk IDs
        run: echo "::set-output name=test-chunk-ids::$(echo $CHUNKS | jq -cM 'to_entries | map(.key)')"
        run: echo "yarn-cache-hit=steps.cache-yarn-cache.outputs.cache-hit != 'true'" >> $GITHUB_OUTPUT
        run: echo "node-modules-cache-hit=steps.cache-node-modules.outputs.cache-hit != 'true'" >> $GITHUB_OUTPUT
        env:
          CHUNKS: ${{ steps['set-test-chunks'].outputs['test-chunks'] }}

  tests:
    name: Test (chunk ${{ matrix.chunk }})
    runs-on: ubuntu-latest
    needs:
      - setup
    env:
      CI: true
    strategy:
      matrix:
        chunk: ${{ fromJson(needs.setup.outputs['test-chunk-ids']) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
      - name: Install Deps
        run: yarn install --frozen-lockfile --prefer-offline
          if: |
          needs.setup.outputs.yarn-cache-hit ||
          needs.setup.outputs.node-modules-cache-hit
      - name: Run tests
        run: echo $CHUNKS | jq '.[${{ matrix.chunk }}] | .[] | @text' | xargs yarn test
        env:
          CHUNKS: ${{ needs.setup.outputs['test-chunks'] }}


